### ISSUE TITLE
Support deepselect on circle and ellipse

### ISSUE THREAD

**Issue by DrSensor** [svgdotjs/svg.select.js#37]
Currently `deepselect` produce 8 points positioned like `rect()`
![screenshot from 2017-12-27 04-49-57](https://user-images.githubusercontent.com/4953069/34365329-aa2cd2c0-eac1-11e7-84c3-2261e6945353.png)

It would be nice to have it produce only 4 points like this
![screenshot from 2017-12-27 04-49-57-2](https://user-images.githubusercontent.com/4953069/34365398-59d88c1e-eac2-11e7-9145-b2bc64c674dd.png)

**Comment by Fuzzyma** [comment]
You can just hide the marker you dont need with css

**Comment by DrSensor** [comment]
For example?

**Comment by Fuzzyma** [comment]
Look at the generated svg and svg.select.css and you will know it.

**Comment by DrSensor** [comment]
I see I need to `fill: none` at edges 

```css
.svg_select_points {
  stroke-width: 1;
  fill: black;
  stroke-dasharray: 10 10;
  stroke: black;
  stroke-opacity: 0.8;
  pointer-events: none; /* This ons is needed if you want to deselect or drag the shape*/
}

.svg_select_boundingRect {
  fill: none;
  stroke: none;
  pointer-events: none; /* This ons is needed if you want to deselect or drag the shape*/
}

.svg_select_points_lt {
  fill: none;
  stroke: none;
  pointer-events: none; /* This ons is needed if you want to deselect or drag the shape*/
}

.svg_select_points_rt {
  fill: none;
  stroke: none;
  pointer-events: none; /* This ons is needed if you want to deselect or drag the shape*/
}

.svg_select_points_rb {
  fill: none;
  stroke: none;
  pointer-events: none; /* This ons is needed if you want to deselect or drag the shape*/
}

.svg_select_points_lb {
  fill: none;
  stroke: none;
  pointer-events: none; /* This ons is needed if you want to deselect or drag the shape*/
}
```

----
However, there is a need to behave originally when select rectangle like this (In my case I need to select multiple elements)
![screenshot from 2017-12-27 06-04-57](https://user-images.githubusercontent.com/4953069/34366279-0ff2132c-eacc-11e7-8c76-d880554885a5.png)

And I notice when I try to return selectize
```javascript
const selector = circle.selectize()
console.log(selector)
```
It returns the circle that I draw, not the `<g>` selector that consist group of `<circle>` (and `<rect>` when I inspect it). Because of it can't be styled using javascript when the selector is circle or eclipse.

Is there any other way to achieve that?
